language: java
jdk:
- oraclejdk8
notifications:
  irc:
    channels:
    - chat.freenode.net#scribble
    on_success: change
    on_failure: change
env:
  global:
  # Ex. travis encrypt -r org/repo GH_USER=your_github_account
  - secure: "jQRKdJlx1KgornSbRKdVMD0rDbB/NOmmdNNAJXcH1+nBI2gyKbKz1xK02A0czojUj8U76tsXAh0uEyZe8baHc93X9yckYTxVOkF50wwR0ocBmhyXx1TGIXld6cUARm3fiD+NcxaNat5TEmeswYENXOBpDIfGGOX89wMGNlcI9cw="
  # Ex. travis encrypt -r org/repo GH_TOKEN=XXX-https://github.com/settings/tokens-XXX
  - secure: "NyfoVI9K+2bkPbSKsKVBVpJePZVEylaqVwZjQX3STOjxszrlH7h9zQgOAdR08fIjhgxlPA02KAdilq/ZQxp2gTsBXJCcOXWyXgaGKVXZIEzSuhLz5cluwDGIFrS/+NJgh8qXX2dGNUgb+/PolhzeuB6S+SwSNmYIINzR4BIfsbk="

install:
- mvn -version -B
script:
- mvn install -B
after_success:
- test "${TRAVIS_BRANCH}" = "pages" && test "${TRAVIS_PULL_REQUEST}" = "false" &&
  mvn -s .travis.settings.xml site
