language: java
jdk:
- oraclejdk8
notifications:
  irc:
    channels:
    - chat.freenode.net#scribble
    on_success: change
    on_failure: change
env:
  global:
  - secure: GlQi/m4dxO5OP+cxM4sk2Ka34sHFbDuiQVUtwls8Z3pTF0f+84z/UfM6jFPrTvrfG8xtlj7AX5BEsxnPFPBKkqmyFiQjfOlq6GJllTqpXJWc5IwKs/4uv2XkJIwZ+z3I6ICAfU/imZJfCPYmODwUsoR6bP3gbQaH/b4/oRXtAd4=
install:
- mvn -version -B
script:
- mvn install -B
after_success:
- test "${TRAVIS_BRANCH}" = "pages" && test "${TRAVIS_PULL_REQUEST}" = "false" &&
  mvn -s .travis.settings.xml site
