language: java
jdk:
- oraclejdk8
notifications:
  irc:
    channels:
    - chat.freenode.net#scribble
    on_success: change
    on_failure: change
env:
  global:
  # Ex. travis encrypt -r org/repo GH_USER=your_github_account
  - secure: "wLofk8WrIrwLixXNRLnPzm8/VO4PUJaHm4wW86jGgJ+GZb8qkN54p/0C4lT/oKtVY45OIKCqqk8fdvjax4Chow8RqLqHrW8MM7xHuykw25guQeB14blzbhMM9L8GbdScmyDn5MRfVuUQXRH+HQD5ScZpNYSgLyKEzpS5r5+PpLM="
  # Ex. travis encrypt -r org/repo GH_TOKEN=XXX-https://github.com/settings/tokens-XXX
  - secure: "fzV6AxqutqwxwrnG+sdHoyylDES+tcaV3kGr507ik42/hYNmCaD9y4y18qdlAvTxcvNbQdzo2jJ4CYuFMJGkt7fxkOhhZJCTfIBjAr9AiV3x+w4rPWK7C2GLzpLhf1vapGxGa+Goq4xF+7VCKxKPNHvBZDN8TQ93w4cW7nLClyE="

install:
- mvn -version -B
script:
- mvn install -B
after_success:
- test "${TRAVIS_BRANCH}" = "pages" && test "${TRAVIS_PULL_REQUEST}" = "false" &&
  mvn -s .travis.settings.xml site
